### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by rKinson** [gstreamer-java/gst1-java-core#114]
On downloading gst1-java-core-0.9.3-javadoc.jar Windows Defender flagged and quarantined the file as a Trojan, specifically Java/Tisifi.C https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aJava%2fTisifi.C&threatid=2147725546

Is this a false positive?

**Comment by neilcsmith-net** [comment]
Yes, as far as I know.  Where did you get the file from?  Slightly odd that the Javadoc is triggering this.  Checked the GitHub download via www.virustotal.com and nothing shows up.

**Comment by neilcsmith-net** [comment]
Not heard further from you so closing.  Thanks.
