### ISSUE TITLE
Having multiple inputs often causes "Most likely this is a multi-threaded client and XInitThreads has not been called"

### ISSUE THREAD

**Issue by zilti** [gstreamer-java/gst1-java-core#131]
My program regularly crashes with this error when I have more than one video input and I'm composing them together:

```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:165: dequeue_pending_request: Zusicherung »!xcb_xlib_unknown_req_in_deq« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
```

nicht erfüllt = not satisfied.

"Abgebrochen (Speicherabzug geschrieben)" = "Aborted (memory dump written)"

Do I have to do something special, or is that a missing call in the wrapper?

**Comment by neilcsmith-net** [comment]
Please provide information on your OS, Java version, JNA version, native GStreamer version, gst1-java-core version etc.  And ideally a simple code example that illustrates your problem, or at least a description of the pipeline you're using and the elements in it.  Is it possible to recreate the pipeline on the CLI with `gst-launch` and if so does it work there?

Thanks!

**Comment by zilti** [comment]
OpenSUSE with Kernel 4.20, OpenJDK 8, JNA 4.5.0, GStreamer 1.14.4, gst1-java-core 0.9.2. I can provide a command line version for gst-launch on tuesday when I'm back in my office, but here's the entire pipeline in both table form and with a graph below it: https://lyrion.ch/opensource/repositories/videocapture/doc/trunk/config.html#org51f77d1(the column "Settings" refers to GStreamer's "Properties", and "Appcaps" is intern stuff from my program, irrelevant here)

**Comment by zilti** [comment]
Here is the CLI version:

```
gst-launch-1.0 \
    compositor name=mix sink_1::xpos=641 sink_1::zorder=1 ! queue ! autovideosink \
    rtspsrc location=rtsp://root:Psy_kpp_video@192.168.0.90/axis-media/media.amp latency=200 ! \
    "application/x-rtp, media=(string)video" ! decodebin sink-caps="video/x-raw" ! queue ! mix. \
    rtspsrc location=rtsp://root:Psy_kpp_video@192.168.0.91/axis-media/media.amp latency=200 ! \
    "application/x-rtp, media=(string)video" ! decodebin sink-caps="video/x-raw" ! queue ! videocrop left=640 ! queue ! mix.
```

**Comment by neilcsmith-net** [comment]
Closing as no further comment.  Please retry with 0.9.4 and JNA 5.2, and get back if this is still an issue and I'll reopen.
