### ISSUE TITLE
Crashes when stop pipeline

### ISSUE THREAD

**Issue by bsceran** [gstreamer-java/gst1-java-core#14]
My java application sometimes crashes when I stop the pipeline. 
The application uses following pipe to play a rtsp stream;
"gst-launch-1.0 rtspsrc location=rtsp://... latency=200 protocols=2 ! rtph264depay ! vaapiparse_h264  ! vaapidecode ! vaapisink".

According to the log file [hs_err_pid19332.txt](https://github.com/gstreamer-java/gst1-java-core/files/282048/hs_err_pid19332.txt), it seems it is related with gstreamer itself but I cannot be sure.

This is my configuration;
Linux localhost.localdomain 3.10.0-327.4.4.el7.x86_64
CentOS Linux release 7.2.1511 (Core)

gstreamer1-1.4.5-1.el7.x86_64
gstreamer1-plugins-base-1.4.5-2.el7.x86_64
gstreamer1-plugins-good-1.4.5-2.el7.x86_64
gstreamer1-plugins-bad-free-1.4.5-3.el7.x86_64
gstreamer1-plugins-bad-freeworld-1.0.6-1.el7.nux.x86_64
gstreamer1-vaapi-0.6.1-1.el7.x86_64

gst1-java-core-0.9-SNAPSHOT

If you need, i can also post the java code itself for reproducing the problem.

**Comment by neilcsmith-net** [comment]
Thanks for the report.  Yes, please attach source code for a short example that replicates this.

Is this behaviour consistent or occasional?

**Comment by bsceran** [comment]
Hi Neil,

I am sorry for late reply. I was busy with implementing a sample
application to reproduce the issue I reported.
My application runs under Sun JDK 1.8 and It rarely crashes when I try to
stop the pipeline.

But somehow, I am not able to reproduce the problem with the sample
application.
Now, I try to make it close to my application in order to narrow the issue.

When I find the reason, I will let you know and provide the sample
application.

Thanks for quick reply.

Serdar CERAN

**Comment by bsceran** [comment]
Hi Neil,

When I testing my sample application [sample-application.zip](https://github.com/gstreamer-java/gst1-java-core/files/286148/sample-application.zip), I have faced with two issues;

1- Player does not start when I first press the PLAY button. But after I press STOP and PLAY button several times, player starts playing.

2- When I resize the frame and canvas, the video does not resize along with them.

Could you please help on these issues?

Serdar

**Comment by bsceran** [comment]
Hi Neil,

Regarding to the issues I had mention 6 days ago, 
I was using vaapisink element to display video. But when I replace it with glimagesink element, 2 issues seems to be fixed now. Additionally, we haven't faced any crash when we try to stop the pipe line.

So, It seems these issues are related with vaapisink implementation, not related to java bindings.

Shall I close this issue then?

**Comment by neilcsmith-net** [comment]
Yes, let's close this, but reopen if you find something that replicates the problem and can't be reproduced upstream.

Thanks, Neil
