### ISSUE TITLE
gst_element_link_filtered is missing from Element-API

### ISSUE THREAD

**Issue by MaZderMind** [gstreamer-java/gst1-java-core#150]
Support for `gst_element_link_filtered`  is missing from the `Element`-API.

**Comment by neilcsmith-net** [comment]
Many things are missing from the API. A pull request with tests would be gratefully received.

**Comment by MaZderMind** [comment]
Thank‘s for the Response, I‘ll open a PR for it.

**Comment by MaZderMind** [comment]
FTR - One can substitute `element.linkFiltered`  with a static call to `Element.linkPadsFiltered`.
These are equivalent:
```
boolean success = Element.linkPadsFiltered(groupTee, "src_%u", panelMixer, "sink_%u", StaticCaps.AUDIO);
boolean success = groupTee.linkFiltered(panelMixer, StaticCaps.AUDIO);
```
