### ISSUE TITLE
Class cast exception in WebRTCPeerConnectionState

### ISSUE THREAD

**Issue by PertsevRoman** [gstreamer-java/gst1-java-core#152]
https://github.com/gstreamer-java/gst1-java-core/blob/a5a2fb09f6a151bd5517452b54d85ce46b929f29/src/org/freedesktop/gstreamer/webrtc/WebRTCBin.java#L265

java.lang.ClassCastException: java.lang.Integer cannot be cast to org.freedesktop.gstreamer.webrtc.WebRTCPeerConnectionState

Maybe I'm not having suitable experience but it happen with standard code

Version 1.0

**Comment by neilcsmith-net** [comment]
Thanks! Yes, not sure how that code was meant to work.  I'm not sure if the underlying native code has type information for this enum, and we don't have code to handle conversion even if it does.  In hindsight we should have required some unit tests before the webrtc PR got merged.
