### ISSUE TITLE
Change func got collected before triggering

### ISSUE THREAD

**Issue by kezhuw** [gstreamer-java/gst1-java-core#176]
There is no strong reference to callback in java for `GstPromiseAPI.ptr_gst_promise_new_with_change_func` in `Promise`'s constructor.

**Comment by neilcsmith-net** [comment]
Yes, that looks rather broken! :roll_eyes: Not sure of best way to fix that - perhaps needs private constructor taking a GstCallback?

**Comment by neilcsmith-net** [comment]
Should be fixed by #200 - please take a look and comment if need be - will aim to merge and release with 1.2 next week.
