### ISSUE TITLE
Set Enum-Properties on Elements by their literal Name

### ISSUE THREAD

**Issue by MaZderMind** [gstreamer-java/gst1-java-core#182]
Enum-Properties on Elements such as the `audiotestsrc`Element can currently only be set via their numeric value:
```
pipeline.getElementByName("test_src").set("wave", 4);
```
It would be very helpful to be also able to use the literal Enum-Value:
```
pipeline.getElementByName("test_src").set("wave", "silence");
```

**Comment by neilcsmith-net** [comment]
Agreed!  In fact, support for setting properties from String in general is something to look at - eg. #166

**Comment by neilcsmith-net** [comment]
@MaZderMind can you take a look at #190 and see if it covers what you need.
