### ISSUE TITLE
Is it possible to add -e flag in java. Because when I start pipeline to save mp4 video - saved video is corrupted

### ISSUE THREAD

**Issue by not404-found** [gstreamer-java/gst1-java-core#198]
gst-launch-1.0 **-e** udpsrc port=some_port

**Comment by neilcsmith-net** [comment]
No, that is a command line only flag, and it is your responsibility to implement what it does in your own project - make sure to shut down the pipeline / post an EOS event as required.

Please use the mailing list for usage questions, thanks.
