### ISSUE TITLE
signal handling no Closure class

### ISSUE THREAD

**Issue by lucgeo** [gstreamer-java/gst1-java-core#201]
Hi,

I worked in the past with Java GStreamer (v0.9.1) and I used for signal handling a class called "Closure". I noticed that in the actual version, this class no longer exist. What any other options do I have? It would be a perfect to have an example.

Thanks,
Lucian

**Comment by neilcsmith-net** [comment]
@lucgeo you should use GObject::connect for this, but it would be good to understand the context you were using Closure to be sure.

Please use the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java for support questions, thanks.  Follow up on this, ideally with an example of the code you were using and what the GObject and signal you're connecting up us.
