### ISSUE TITLE
Buffer has no PTS.

### ISSUE THREAD

**Issue by honcharenko-roman** [gstreamer-java/gst1-java-core#203]
While using gst-java wrapper and omxh264enc on Raspberry pi, encoding failing with "Buffer has no PTS" issue. 
It's a well-known issue, it has been worked around. In Python I can do:

`GstBase.BaseParse.set_infer_ts(h264parse_element, True)`
`GstBase.BaseParse.set_pts_interpolation(h264parse_element, True)`

Is it possible to do basically the same thing in Java? I didn't found BaseSrc class extended from Element as it documented by GStreamer. 

![image](https://user-images.githubusercontent.com/46729793/89037153-ad7c5700-d346-11ea-87cf-6762f6cd5c31.png)

![image](https://user-images.githubusercontent.com/46729793/89037310-eb797b00-d346-11ea-856e-604dd4e228e6.png)

 I'm using org.freedesktop.gstreamer library version 0.9.4, tried last one - 1.2, but the result is the same.
Java 8

**Comment by neilcsmith-net** [comment]
GstBaseParse isn't mapped at present. I'm not sure if there's another workaround? These settings aren't exposed as properties as far as I can tell, so generic GObject::set is out. There is also the ability to set PTS directly on the Buffer.

Obviously, a PR to map GstBaseParse would be ideal :smile: but you could also map the functions you need directly using JNA, and extract the raw pointer from the element using the Natives class.

Don't use 0.9.4 by the way.  Lots of changes and fixes between there and 1.2, including the above mentioned Natives class.

**Comment by honcharenko-roman** [comment]
Thanks a lot for a fast response! I will continue digging and investigating in directions you pointed.

**Comment by honcharenko-roman** [comment]
For those who are looking for a solution (not quite sure about gstapp but works well):
![image](https://user-images.githubusercontent.com/46729793/89264809-398ac900-d63c-11ea-91e4-cbd7cb979314.png)

And use:
![image](https://user-images.githubusercontent.com/46729793/89264828-414a6d80-d63c-11ea-8d2f-b20e79f62f0c.png)

Probably later will do a PR with GstBaseParse implementation.
