### ISSUE TITLE
Take a snapshot at request.

### ISSUE THREAD

**Issue by honcharenko-roman** [gstreamer-java/gst1-java-core#207]
Hi, I'm trying to figure out how to add elements to the already playing pipeline.
I'm taking video stream from uvc camera with v4l2src, then saving it to files by splitmuxsink. but I want to be able to get an actual snapshot. Right now I implemented this by tee element and endless RTP stream. On-demand I just connecting to it and saving a single frame.
What is the better approach? For example, open the stream on-demand and close the stream after taking a snapshot. Thanks for your answer!

**Comment by neilcsmith-net** [comment]
Please use the mailing list for support questions, thanks.
