### ISSUE TITLE
How to receive each frame as its pointer(Long type) or Byte array or etc.

### ISSUE THREAD

**Issue by dayo05** [gstreamer-java/gst1-java-core#252]
I want to decode some video and print it by lwjgl(Java binding of OpenGL) and I want to receive data from gstreamer.

I want to do like
```java
Long currentFramePtr = playbin.getCurrentFrame();
GL21.glTexImage2D...
```
or
```java
ByteArray currentFrameData = playbin.getCurrentFrame();
GL21.glTexImage2D...
```

If it exists, can I see example of that?

**Comment by neilcsmith-net** [comment]
Please use the mailing list or discussions for usage questions, thanks.
