### ISSUE TITLE
procedures to compile 

### ISSUE THREAD

**Issue by Abu-Abdullah** [gstreamer-java/gst1-java-core#38]
hi,

please provide guidlines on how to compile this library. i tried to compile it with maven in IntelliJ but no luck. non of the tasks are able to generate the library.

it will be great if you can have public repository with updated binaries all the time.

**Comment by smarquard** [comment]
You should be able to build and install it into your local maven repo with:

git clone https://github.com/gstreamer-java/gst1-java-core.git 
cd gst1-java-core ; mvn clean install

**Comment by Abu-Abdullah** [comment]
thanks, it works in linux. i was trying from windows machine but it seems fairly easy in linux
