### ISSUE TITLE
How about make gst1-java can be assemblied

### ISSUE THREAD

**Issue by knightpop** [gstreamer-java/gst1-java-core#56]
Now, gst1-java is not on maven. So, I think best way to use user library is package jar and use. So, how about add maven-assembly plugin? I will send you pull request

**Comment by neilcsmith-net** [comment]
What does this give us beyond the JAR already available from the Releases
tab?

**Comment by knightpop** [comment]
Oh, Sorry I didn't notice.... But also, It`s because your jar did not contain dependencies. Can it be used stand alone? I think i have to contain jna in my project. It`s little bothering

**Comment by woglinde** [comment]
It is a library and no application so we do not need to assemble anything. When pushed to a maven repository it will have a pom.xml which defines all dependencies and you should use the maven/gradle way to include the lib and not import the jar standalone.

**Comment by neilcsmith-net** [comment]
Thanks @woglinde That was my thought too.  The JAR is just a convenience, particularly for those of us not using Maven in projects (eg. Praxis LIVE is still Ant based).  It's there to stop me having to point anyone who asks for a pre-built JAR to the Praxis LIVE repository! :smile: Building from source is still the better option until we're release ready.
