### ISSUE TITLE
pipeline I/O to and from java Streams

### ISSUE THREAD

**Issue by jcable** [gstreamer-java/gst1-java-core#66]
Hi, I'd like to feed a pipeline from a java InputStream and pipe the output of the pipeline to a java OutputStream.

Do you have any suggestions as to the best approach to take?

**Comment by neilcsmith-net** [comment]
You'll probably need to make use of AppSrc and AppSink. These give you native bytebuffers that you can fill from the streams. Or possibly something with GStreamer's TCP/UDP sources and sinks, and a localhost connection?

For general usage questions, please sign up to the GStreamer-Java mailing list at https://groups.google.com/forum/#!forum/gstreamer-java

Thanks, Neil

**Comment by jcable** [comment]
Thanks Neil, I'll take a look in that direction
