### ISSUE TITLE
Could not load library: gstreamer

### ISSUE THREAD

**Issue by E-two** [gstreamer-java/gst1-java-core#68]
Hello, excuse me, could you tell me how to deal with the mistake of "java.lang.UnsatisfiedLinkError: Could not load library: GStreamer"?

**Comment by woglinde** [comment]
You need to provide more context, which OS, which Linux-Distribution and so on, you are running gstreamer-java.

A common problem with most linux distribution is, that JNA which is used to load the libraries, only loads libraries with the suffix .so. These libs or links are often provided in the  -dev packages.

**Comment by E-two** [comment]
I gst1-java-core project with Maven build, and then use the gst1-java-examples project in the CameraTest test, the "Exception in thread" main "java.lang.UnsatisfiedLinkError: Could not load library: GStreamer" bug, I run the platform is windows. Thank you.

**Comment by woglinde** [comment]
You also need to install gstreamer1 for windows. gstreamer-java is merely a wrapper for gstreamer, with some java sugar. Ich you already have installed gstreamer1, you proably need to set the jvm jna.library.path variable to the directory where .dll are located.

**Comment by neilcsmith-net** [comment]
There are various potential reasons for this -

- You haven't installed GStreamer 1.x - you can find installers at https://gstreamer.freedesktop.org/data/pkg/windows/1.12.0/ eg. for 64-bit use https://gstreamer.freedesktop.org/data/pkg/windows/1.12.0/gstreamer-1.0-x86_64-1.12.0.msi
- You have a mismatch between 32bit/64bit JVM and GStreamer.
- GStreamer isn't in your PATH. Note @woglinde suggestion about `jna.library.path` will only get you part of the way on Windows. You can add GStreamer to your system path, or use JNA's optional Platform library to set up environment variables like I do at https://github.com/praxis-live/praxis/blob/master/praxis.video.gst1/src/net/neilcsmith/praxis/video/gst1/components/GStreamerLibrary.java#L50

This isn't an issue with gst1-java-core so I'm closing this.  For usage issues please use the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java as linked in the Readme.

Feel free to add a feature request here for further documentation though! This is a high priority so knowing exactly what would have made this easier for you will help.

Thanks, Neil

**Comment by E-two** [comment]
Thank you very much, woglinde and neilcsmith-net. I should know what to do, thank you!
