### ISSUE TITLE
Is there a RTSPBin like PlayBin?

### ISSUE THREAD

**Issue by E-two** [gstreamer-java/gst1-java-core#69]
I've just been in touch with GStreamer. I found a PlayBin in gst1-java-core that plays the local MP3 very well. I'd like to ask if you can write a RTSPBin like this. Thanks.

**Comment by neilcsmith-net** [comment]
Can you provide a C or other coding sample of what you're trying to do?  You should be able to achieve it within the current API.  You don't _need_ a custom element for most things - a small number of common ones are provided as a convenience.  That's not making any judgement right now on whether this should or shouldn't be one of them.

**Comment by E-two** [comment]
Because of the unit test examples and the gst1-java-examples project example, I haven't found examples of screenshots of video streams after the camera or RTSP stream is captured. I'm sorry to have caused you so much trouble, but I just got in touch. It's really difficult for me.

**Comment by neilcsmith-net** [comment]
@E-two That's OK!  Please sign up and ask for help on the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java  Hopefully other users can input then, and we can work out what if any changes need to be made to the core to support what you want to do.  I'll close this for now.  Thanks, Neil

**Comment by E-two** [comment]
@Neil, Thank you very much. I'll register and ask for help via email.
