### ISSUE TITLE
Gst.init() Gst.deinit() issue

### ISSUE THREAD

**Issue by lucgeo** [gstreamer-java/gst1-java-core#70]
Hi,

I use the gstreamer java library and I have an issue for which I cannot find any solution at this time. 
The idea is that I want to start from the main class a new thread running a class that contains gstreamer code. This class contains the Gst.init() statement, and in the end, if I call Gst.deinit(), new threads will not run properly afterwards. Gst.deinit() doesn't seem to completely cancel the previous initialization. Otherwise, if I don't call Gst.deinit(), I can start new threads and these will run, but the memory will not be released at the end of the execution, so after starting multiple threads, the memory will be full.
I still have an idea:
I have noticed that all functions in the Gst class are static functions. I suspect this is a problem, so I would try to turn them into non-static. Would I solve something if I do that?
What other solution do you recommend?

Thank you!

**Comment by neilcsmith-net** [comment]
You almost certainly _do not_ want to call `Gst.deinit()` - please see the documentation of this function upstream - https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gstreamer-Gst.html#gst-deinit

How are you measuring that memory is not released, and what exactly is remaining in memory?

**Comment by lucgeo** [comment]
Hi,

Thank you for your answer.
I measure the memory running "htop" command on Linux. I use a custom gstreamer element: https://github.com/alumae/gst-kaldi-nnet2-online. It is a gstreamer module created around a text-to-speech decoder that uses the Kaldi toolkit.
All I want is to have a main class that runs continuously on a server. From this I can start new threads in which I initialize a new gstreamer pipeline and I add to it this custom speech decoder element. For this element I set some attributes that consumes a very significant amount of memory. At the end of the thread execution I want to release the memory occupied by this element. I'm almost sure the resources of this element are remaining in memory now.

**Comment by neilcsmith-net** [comment]
Are you manually disposing the pipelines when you're done with them?  If all the heavy memory usage is outside of the JVM heap then relying on GC to collect it might be a problem.

**Comment by lucgeo** [comment]
I'm not sure if I understand correctly what you mean by "manual disposing," but in the thread where I run gstreamer, when the task is done, I call something like "pipe.setState (State.NULL)" and "pipe.dispose () ".

**Comment by neilcsmith-net** [comment]
Exactly that, yes!  So, it's possible you've uncovered a memory leak in the bindings, or a memory leak in the custom element, or something else.  Now you just need to find which. :smile: Can you monitor with VisualVM?  Try seeing if there are any objects under `org.freedesktop.gstreamer` being kept in memory longer than expected.

What are these attributes that you're setting?  How do you set them?

**Comment by lucgeo** [comment]
I attach here a snippet to exemplify how I create the custom element and I set its attributes.
`asr = ElementFactory.make("kaldinnet2onlinedecoder", "asr");
        asr.set("nnet-mode", NNET_RECIPE_TYPE);
        asr.set("use-threaded-decoder", FALSE);
        asr.set("fst", DECODING_GRAPH);
        asr.set("model", MODEL);
        asr.set("word-syms", WORDS);
        asr.set("feature-type",FEATURE_TYPE);
        asr.set("mfcc-config", MFCC_CONFIG);
        asr.set("ivector-extraction-config", IVECTOR_EXTRACTION_CONFIG);
        asr.set("endpoint-silence-phones", SILENCE_PHONES);
        asr.set("max-active", MAX_ACTIVE);
        asr.set("beam", BEAM);
        asr.set("lattice-beam", LATTICE_BEAM);
        asr.set("acoustic-scale", ACOUSTIC_SCALE);
        asr.set("lm-fst", DECODING_LM_FST);   
        asr.set("big-lm-const-arpa", RESCORING_LM_FST);
        asr.set("phone-syms", PHONES);
        asr.set("word-boundary-file", WORD_BOUNDARY);
        asr.set("silent", SILENT);
        asr.set("do-phone-alignment", PHONE_ALIGNMENT);
        asr.set("do-endpointing", ENDPOINTING);`

For example, the decoding graph (DECODING_GRAPH), acoustic model (MODEL) and the decoding / rescoring language model (DECODING_LM_FST, RESCORING_LM_FST) are quite large resources.

I will inspect the issue with Visual VM and come back with info.

**Comment by neilcsmith-net** [comment]
But what Java types are MODEL, etc?

**Comment by lucgeo** [comment]
They are not standard Java data types. "Model" represents the path to a file created using Kaldi speech recognition toolkit.

**Comment by neilcsmith-net** [comment]
They _have_ to  be a Java type of some sort!  Just trying to figure out if you're passing anything in that might hold a significant amount of memory on the Java side, or whether everything is allocated by the custom element.  eg. assuming a path, you're passing in something like String or URI and the custom element is loading the data?

**Comment by lucgeo** [comment]
Exactly, the custom element is loading the data.

**Comment by neilcsmith-net** [comment]
Closing this for now. Please open another issue if you find a cause of memory leaks on our end rather than in the GStreamer plugin. Thanks, Neil
