### ISSUE TITLE
Complete removal of legacy GStreamer 0.10 mappings

### ISSUE THREAD

**Issue by neilcsmith-net** [gstreamer-java/gst1-java-core#76]
There are still some remaining mappings and functionality related to GStreamer 0.10 that need assessing, updating or removing prior to stabilising the API.

**Comment by i-n-g-o** [comment]
started to cleanup lowlevel, removing deprecated methods, adapting to (some) API changes.
(of course this is work in progess ;) )
target is API 1.8.

please have a look here:
https://github.com/i-n-g-o/gst1-java-core/tree/cleanup_lowlevel

i suggest to sort the classes in on lowlevel the way they are documented:
https://gstreamer.freedesktop.org/data/doc/gstreamer/1.8/

**Comment by i-n-g-o** [comment]
started aligning the structures: #112
