### ISSUE TITLE
Plans for higher level abstractions

### ISSUE THREAD

**Issue by woglinde** [gstreamer-java/gst1-java-core#8]
Are there any plans to support the higher level abstractions like SWTOverlay or PipelineMediaPlayer in one or multiple packages?

I need both and got the SWT stuff workinkg last week by copying over the needed pices to core and some tweaking.

**Comment by neilcsmith-net** [comment]
Hi Henning,

CC'ing mailing list.

On 7 March 2016 at 12:11, Henning Heinold <notifications@github.com> wrote:

> Are there any plans to support the higher level abstractions like
> SWTOverlay or PipelineMediaPlayer in one or multiple packages?
>
> I need both and got the SWT stuff workinkg last week by copying over the
> needed pices to core and some tweaking,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gstreamer-java/gst1-java-core/issues/8>.
>

High-level abstractions were deliberately removed from gst1-java-core - the
-core suffix is about modularising the code.  Support for SWT would ideally
go in a separate gst-java-swt module / repository with a dependency on
gst1-java-core.  Likewise for Swing and some other things.

There were a number of other reasons SWT specifically was removed too - a)
having unmet dependencies causes warnings in some build systems when using
the library, and b) I don't use and have no desire to learn SWT, so you
don't want me working on it! ;-)

So, if you or anyone else would be up for working on and maintaining
gst1-java-swt, give me a shout and I'll set up a repository for you within
the gstreamer-java GitHub organisation.

Obviously, feel free to file necessary pull requests against
gst1-java-core, as long as they don't bring in external dependencies.

Hope that helps.

Best wishes,

Neil

-- 
Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

Praxis LIVE - hybrid visual IDE for creative coding - www.praxislive.org
Digital Prisoners - interactive spaces and projections -
www.digitalprisoners.co.uk

**Comment by woglinde** [comment]
I would glady maintain a gst1-java-swt repository and could provide the code fastly.

The first step is in pull request #9.

**Comment by neilcsmith-net** [comment]
On 7 March 2016 at 15:13, Henning Heinold <notifications@github.com> wrote:

> I would glady maintain a gst1-java-swt repository and could provide the
> code fastly.
>
> The first step is in pull request #9
> <https://github.com/gstreamer-java/gst1-java-core/pull/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gstreamer-java/gst1-java-core/issues/8#issuecomment-193292156>
> .
>

Done!  You are now the proud admin of a bare gstreamer-java/gst1-java-swt
repository.

Best wishes,

Neil

-- 
Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

Praxis LIVE - hybrid visual IDE for creative coding - www.praxislive.org
Digital Prisoners - interactive spaces and projections -
www.digitalprisoners.co.uk

**Comment by neilcsmith-net** [comment]
I will look at #9 ASAP. Closing this issue.
