### ISSUE TITLE
Try to use "gnlurisource" element from the Gnonlin

### ISSUE THREAD

**Issue by lucgeo** [gstreamer-java/gst1-java-core#85]
Hi,

I would like to know if Java Gstreamer binding supports the use of "gnlsource" element instead of filesrc. I want to read from an audio file just a segment, knowing the timestamps. I managed to do this directly fromthe terminal, using gst-launch, but I have problems implementing this pipeline in Java. Here I have described exactly what I did and I gave a code snippet: [https://stackoverflow.com/questions/46504029/java-gstreamer-gnonlin-source-segmentation](https://stackoverflow.com/questions/46504029/java-gstreamer-gnonlin-source-segmentation)

Thanks!

**Comment by neilcsmith-net** [comment]
I don't know the gnlurisource element, but from its docs it looks like it has a src pad that's only sometimes there.  In that case, if you create the elements all manually, you'll have to handle the right messages and connect the pads when ready.

Alternatively, the easier approach is to use `Pipeline.launch()` or `Bin.launch()`.  Try the first with the pipeline that works for you on the command line.  Both of these delegate dynamic connection to GStreamer, so it's easier and less code.  You can always get specific elements out of a pipeline or bin by giving them a name and calling `getElementByName()`.

**Comment by neilcsmith-net** [comment]
No follow up so closing. Please reopen if you need more help.
