### ISSUE TITLE
Are there known memory leaks?

### ISSUE THREAD

**Issue by zilti** [gstreamer-java/gst1-java-core#91]
I have a rather simple pipeline, consisting of a v4l2src, a pulsesrc, an appsink with a display I used from the JavaFX sample, and a encoder which is turned off via a valve.

GStreamer leaks about 80 Megabytes per second(!!). Where do I start looking for the cause? That's ridiculous.

**Comment by neilcsmith-net** [comment]
No, there are no _known_ memory leaks, funnily enough!  There's a chance there may be some unknown ones.  However, I think it's unlikely there's anything of that magnitude.

It sounds like somewhere your code is not releasing the video buffers.  Can you post a small example ([MVCE](https://stackoverflow.com/help/mcve)) that illustrates the bug?

Ideally, sign up to the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java and post it there - if there's an actual issue we can follow up with it here later.

**Comment by zilti** [comment]
I think I have this fixed - it turns out the laptop I got as testing platform for the video recording tool was simply *too slow* - it had a third-gen mobile i3 CPU. The exact same tool didn't leak a byte on a faster machine.
