### ISSUE TITLE
Clarification of requirments

### ISSUE THREAD

**Issue by TalaatHarb** [gstreamer-java/gst1-java-core#92]
It should be more clear which GStreamer installer is required for the gst1-java-core to work, I suggest adding it to the requirement section in the  README.md.
The reason I said that is that the developer will see all those files when trying to download the framework for windows: 
  | gstreamer-1.0-devel-x86-1.12.4.msi | 2017-12-10 02:30 | 124M |  
  | gstreamer-1.0-devel-x86-1.12.4.msi.asc | 2017-12-10 06:11 | 801 |  
  | gstreamer-1.0-devel-x86-1.12.4.msi.sha256sum | 2017-12-10 06:13 | 101 |  
  | gstreamer-1.0-devel-x86_64-1.12.4.msi | 2017-12-10 02:30 | 132M |  
  | gstreamer-1.0-devel-x86_64-1.12.4.msi.asc | 2017-12-10 06:11 | 801 |  
  | gstreamer-1.0-devel-x86_64-1.12.4.msi.sha256sum | 2017-12-10 06:13 | 104 |  
  | gstreamer-1.0-x86-1.12.4-merge-modules.zip | 2017-12-10 02:30 | 114M |  
  | gstreamer-1.0-x86-1.12.4-merge-modules.zip.asc | 2017-12-10 06:11 | 801 |  
  | gstreamer-1.0-x86-1.12.4-merge-modules.zip.sha256sum | 2017-12-10 06:13 | 109 |  
  | gstreamer-1.0-x86-1.12.4.msi | 2017-12-10 02:30 | 115M |  
  | gstreamer-1.0-x86-1.12.4.msi.asc | 2017-12-10 06:11 | 801 |  
  | gstreamer-1.0-x86-1.12.4.msi.sha256sum | 2017-12-10 06:13 | 95 |  
  | gstreamer-1.0-x86_64-1.12.4-merge-modules.zip | 2017-12-10 02:30 | 122M |  
  | gstreamer-1.0-x86_64-1.12.4-merge-modules.zip.asc | 2017-12-10 06:11 | 801 |  
  | gstreamer-1.0-x86_64-1.12.4-merge-modules.zip.sha256sum | 2017-12-10 06:13 | 112 |  
  | gstreamer-1.0-x86_64-1.12.4.msi | 2017-12-10 02:30 | 123M |  
  | gstreamer-1.0-x86_64-1.12.4.msi.asc | 2017-12-10 06:12 | 801 |  
  | gstreamer-1.0-x86_64-1.12.4.msi.sha256sum | 2017-12-10 06:13 | 98 |  

and only one of this files will work for his JVM+JNA configuration.

**Comment by neilcsmith-net** [comment]
Thanks! Agreed, some better clarification / installation documentation would be useful. I'll look at something for the README, although you could also make a PR or create a wiki page (permissions should be open).

Note there is also the GStreamer documentation https://gstreamer.freedesktop.org/documentation/ and https://gstreamer.freedesktop.org/documentation/installing/on-windows.html

**Comment by TalaatHarb** [comment]
Thanks, I will gain more experience with it and see how I can help.
