### ISSUE TITLE
busMessage() silently catches exceptions

### ISSUE THREAD

**Issue by piegamesde** [gstreamer-java/gst1-java-core#99]
I spent the last half hour tracking down why my code wasn't executed to find out the the `busMessage()` callback silently caught my NullPointerException. Other callbacks are probably affected too.

**Comment by neilcsmith-net** [comment]
Can you give me a bit more of a clue about your code that was failing and where?

**Comment by piegamesde** [comment]
I did

	bus.connect(new Bus.MESSAGE() {
		@Override
		public void busMessage(Bus bus, Message message) {
		}
	});

Inside the `busMessage` a `RuntimeException` was thrown. The method caller caught it silently without dumping a stack trace.

**Comment by neilcsmith-net** [comment]
OK, thanks.  Quick look suggests these are called on the executor service, so this is kind of expected behaviour.  May need to consider a better approach, although only if we can do it without impacting performance of correctly functioning code.

**Comment by MaZderMind** [comment]
The straight forward way would be to wrap `bus.dispatchMessage(msg);` in `GstBusAPI.BusSyncHandler#callback` with a try-catch and log the exception there.

This would solve the Problem of the Exception being invisible (which did bite me more then once, too) while not adding any burden on correctly functioning code.

**Comment by MaZderMind** [comment]
As a side note: Catching Exceptions within the Runnable seems to be good practice anyway: https://stackoverflow.com/a/24902026/1659732

**Comment by neilcsmith-net** [comment]
Yes, potentially we could add something in https://github.com/gstreamer-java/gst1-java-core/blob/master/src/org/freedesktop/gstreamer/Bus.java#L733

Although I'm more inclined to an uncaught exception handler in https://github.com/gstreamer-java/gst1-java-core/blob/master/src/org/freedesktop/gstreamer/Gst.java#L654  (and removing the applet check!)

Catching Exception is not enough - we also need to be reporting at least UnsatisfiedLinkError.

**Comment by neilcsmith-net** [comment]
OK, the uncaught exception handler approach doesn't work due to the architecture of the executor anyway.  So, catching and logging Throwable at https://github.com/gstreamer-java/gst1-java-core/blob/master/src/org/freedesktop/gstreamer/Bus.java#L838 This is per message handler, so other handlers will still receive the message, which seems the right approach.
